# ---------------------------------------------------------------------------
# SSH key pair — generated by Terraform, public half registered in AWS,
# private half written to a local .pem file (0400) for you to use.
# ---------------------------------------------------------------------------

resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = var.key_name
  public_key = tls_private_key.ssh.public_key_openssh

  tags = {
    Name = "${var.project_name}-key"
  }
}

# NOTE: the private key ends up in the Terraform state file as well as this
# local file. Make sure your state backend is encrypted (or at minimum kept
# out of version control) if you go this route.
resource "local_file" "private_key" {
  filename        = "${path.module}/${var.key_name}.pem"
  content         = tls_private_key.ssh.private_key_pem
  file_permission = "0400"
}
